version: '3.8'

services:

  postgres:
    image: postgres:16
    container_name: keycloak-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      restart: unless-stopped
      depends_on:
        - postgres
      environment:
        KEYCLOAK_ADMIN: admin
        KEYCLOAK_ADMIN_PASSWORD: admin123
        KC_DB: postgres
        KC_DB_URL_HOST: postgres
        KC_DB_URL_PORT: 5432
        KC_DB_URL_DATABASE: keycloak
        KC_DB_USERNAME: keycloak
        KC_DB_PASSWORD: keycloak123
        # KRİTİK DEĞİŞİKLİK BURADA:
        KC_HOSTNAME: localhost
        KC_HOSTNAME_STRICT: "false"
        KC_HOSTNAME_STRICT_HTTPS: "false"
      ports:
        - "8080:8080"
      command: start-dev

  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"      

  postgres_ticket:
    image: postgres:16
    container_name: ticket-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ticketdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    command:
      - postgres
      - -c
      - wal_level=logical
      - -c
      - max_replication_slots=4
      - -c
      - max_wal_senders=4
    volumes:
      - ticket_postgres_data:/var/lib/postgresql/data

  kafka:
      image: apache/kafka:3.9.0
      container_name: kafka
      restart: unless-stopped
      ports:
        - "9092:9092"
        - "9094:9094"
      environment:
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://:29092,EXTERNAL://0.0.0.0:9092,MINIKUBE://0.0.0.0:9094,CONTROLLER://:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,EXTERNAL://192.168.1.2:9092,MINIKUBE://host.minikube.internal:9094
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT,MINIKUBE:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  connect:
    image: debezium/connect:2.7.3.Final
    container_name: debezium-connect
    restart: unless-stopped
    depends_on:
      - kafka
      - postgres_ticket
    ports:
      - "8083:8083"
    environment:
      BOOTSTRAP_SERVERS: kafka:29092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: connect_configs
      OFFSET_STORAGE_TOPIC: connect_offsets
      STATUS_STORAGE_TOPIC: connect_statuses
      CONFIG_STORAGE_REPLICATION_FACTOR: 1
      OFFSET_STORAGE_REPLICATION_FACTOR: 1
      STATUS_STORAGE_REPLICATION_FACTOR: 1
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      KEY_CONVERTER_SCHEMAS_ENABLE: "false"
      VALUE_CONVERTER_SCHEMAS_ENABLE: "false"
      PLUGIN_PATH: /kafka/connect
      CONNECT_OFFSET_STORAGE_CLEANUP_POLICY: "compact"
      CONNECT_CONFIG_STORAGE_CLEANUP_POLICY: "compact"
      CONNECT_STATUS_STORAGE_CLEANUP_POLICY: "compact"

  kafdrop:
    image: obsidiandynamics/kafdrop:latest  
    container_name: kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - kafka

volumes:
  mysql_data:
  postgres_data:
  ticket_postgres_data: