apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service-container
          image: docker.io/library/notification-service:v2
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8503
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: notification-service-secret
          env:
            - name: SERVER_PORT
              value: "8503"
          resources:
            requests:
              cpu: "250m"      
              memory: "256Mi"
            limits:
              cpu: "500m"     
              memory: "512Mi"    