apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service-container
          # 🔴 DEĞİŞEN SATIR: Minikube listesindeki tam ismi verdik
          image: docker.io/library/notification-service:v2
          # 💡 İPUCU: İmaj lokalde zaten var olduğu için 'Always' yerine 'IfNotPresent' yaparsak
          # Kubernetes dışarıdan (internet üzerinden) çekmeye çalışmaz, direkt lokaldekini kullanır.
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8503
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: notification-service-secret
          env:
            - name: SERVER_PORT
              value: "8503"
          resources:
            requests:
              cpu: "250m"      # 0.25 Core - Gerçekçi başlangıç değeri
              memory: "256Mi"
            limits:
              cpu: "500m"      # En fazla 0.5 Core
              memory: "512Mi"    