server:
  port: 8503

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: notification-service

  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123        



management:
  tracing:
    sampling:
      probability: 1.0
    propagation:
      produce: [W3C, B3]
      consume: [W3C, B3]
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "health,info,tracing"
