apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  SERVER_PORT: "8504"
  SPRING_APPLICATION_NAME: "gateway-service"

  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8080/realms/master"

  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_DISCOVERY_LOCATOR_ENABLED: "false"

  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_ID: "ticket-service-route"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_URI: "http://ticket-service:8502"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_PREDICATES_0: "Path=/api/ticket/**"
  SPRING_CLOUD_GATEWAY_SERVER_WEBFLUX_ROUTES_0_FILTERS_0: "TokenRelay"

  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://host.minikube.internal:9411/api/v2/spans"

  MANAGEMENT_TRACING_PROPAGATION_PRODUCE_0: "W3C"
  MANAGEMENT_TRACING_PROPAGATION_PRODUCE_1: "B3"
  MANAGEMENT_TRACING_PROPAGATION_CONSUME_0: "W3C"
  MANAGEMENT_TRACING_PROPAGATION_CONSUME_1: "B3"

  MANAGEMENT_ENDPOINT_HEALTH_PROBES_ENABLED: "true"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,tracing"