apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-app
  template:
    metadata:
      labels:
        app: gateway-app
    spec:
      hostAliases:
        - ip: "192.168.49.2"
          hostnames:
            - "auth.test"
            - "apigateway.test"
      containers:
        - name: gateway-container
          image: ysfaksn/api-gateway:a6b2e7d3daa261c857d820eec35f956ddea7ce5b
          imagePullPolicy: Always
          ports:
            - containerPort: 8504
          envFrom:
            - configMapRef:
                name: gateway-config