apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway-service-monitor
  namespace: monitoring
  labels:
    release: monitoring

spec:
  selector:
    matchLabels:
      app: gateway-service

  namespaceSelector:
    matchNames:
      - default

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s