apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-config
data:
  SERVER_PORT: "8502"
  SPRING_APPLICATION_NAME: ticket-service

  # PostgreSQL JDBC driver configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.minikube.internal:5434/ticketdb"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password" 

  # Tracing (Zipkin) 
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://host.minikube.internal:9411/api/v2/spans

  # Security (Keycloak) 
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://keycloak:8080/realms/master"