apiVersion: v1
kind: ConfigMap
metadata:
  name: ticket-service-config
data:
  SERVER_PORT: "8502"
  SERVER_SHUTDOWN: "graceful"
  SPRING_APPLICATION_NAME: "ticket-service"
  SPRING_LIFECYCLE_TIMEOUT_PER_SHUTDOWN_PHASE: "30s"

  # PostgreSQL JDBC driver configuration
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.minikube.internal:5434/ticketdb"
  SPRING_DATASOURCE_USERNAME: "user"
  SPRING_DATASOURCE_PASSWORD: "password"
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"

  # HikariCP connection pool
  SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT: "5000"
  SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT: "3000"
  SPRING_DATASOURCE_HIKARI_MAX_LIFETIME: "1700000"

  # JDBC Observation (Micrometer SQL Tracing)
  JDBC_DATASOURCE_PROXY_ENABLED: "true"
  JDBC_INCLUDES: "query,fetch"

  # Tracing (Zipkin & Micrometer)
  MANAGEMENT_TRACING_SAMPLING_PROBABILITY: "1.0"
  MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: "http://host.minikube.internal:9411/api/v2/spans"

  # Security (Keycloak)
  SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI: "http://auth.test/realms/master"

  # Resilience4j Circuit Breaker
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_TICKET_DB_SLIDING_WINDOW_TYPE: "COUNT_BASED"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_TICKET_DB_SLIDING_WINDOW_SIZE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_TICKET_DB_MINIMUM_NUMBER_OF_CALLS: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_TICKET_DB_FAILURE_RATE_THRESHOLD: "50"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_TICKET_DB_WAIT_DURATION_IN_OPEN_STATE: "30s"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_TICKET_DB_PERMITTED_NUMBER_OF_CALLS_IN_HALF_OPEN_STATE: "5"
  RESILIENCE4J_CIRCUITBREAKER_INSTANCES_TICKET_DB_AUTOMATIC_TRANSITION_FROM_OPEN_TO_HALF_OPEN_ENABLED: "true"