apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      hostAliases:
        - ip: "192.168.49.2"
          hostnames:
            - "auth.test"
            - "apigateway.test"
      containers:
        - name: ticket-service-container
          image: ysfaksn/ticket-service:a6b2e7d3daa261c857d820eec35f956ddea7ce5b
          imagePullPolicy: Always
          ports:
            - containerPort: 8502
          envFrom:
            - configMapRef:
                name: ticket-service-config
            - secretRef:
                name: ticket-service-secret
          env:
            - name: SERVER_PORT
              value: "8502"
          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"