apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ticket-service
  template:
    metadata:
      labels:
        app: ticket-service
    spec:
      containers:
        - name: ticket-service-container
          image: docker.io/library/ticket-service:v10
          imagePullPolicy: IfNotPresent 
          ports:
            - containerPort: 8502
          envFrom:
            - configMapRef:
                name: ticket-service-config
            - secretRef:
                name: ticket-service-secret
          env:
            - name: SERVER_PORT
              value: "8502"
          resources:
            requests:
              cpu: "250m"      # 0.25 Core - Gerçekçi başlangıç değeri
              memory: "256Mi"
            limits:
              cpu: "500m"      # En fazla 0.5 Core
              memory: "512Mi"    