apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ticket-query-service
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/yusufaksn/microservices-infrastructure.git
    targetRevision: main
    path: ticket-service-query/k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: ticket-service-query

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true